### PR TITLE
Merge dragonball branch into master

### PR DESCRIPTION
**Pull request by arronwy**
Looking to merge dragonball branch into master #8

### CODE REVIEW

**Comment by rbradford** [comment]
Wouldn't it be better to merge it into rust-vmm/vhost instead?

**Comment by arronwy** [comment]
> Wouldn't it be better to merge it into rust-vmm/vhost instead?

Current stage we prefer merge it in cloud-hypervisor/vhost :-)

**Comment by sameo** [comment]
@arronwy Could you explain what is the benefit of doing so?
This crate is a mirror of the rust-vmm one, so I feel it would be better to have the master branch being the mirror and the dragonball one our collaboration one.

The natural next step for this crate would be for us to submit our changes upstream and eventually switch to it from Cloud Hypervisor.

**Comment by arronwy** [comment]
> @arronwy Could you explain what is the benefit of doing so?
> This crate is a mirror of the rust-vmm one, so I feel it would be better to have the master branch being the mirror and the dragonball one our collaboration one.
> 
> The natural next step for this crate would be for us to submit our changes upstream and eventually switch to it from Cloud Hypervisor.


We thought it may cost less effort to upstream in current repository,  since submit to rust-vmm will be the right way, I'll resubmit to rust-vmm/vhost.

**Pull request closed without merging**
