### PR TITLE
Add a crate to support vhost backend drivers for virtio devices

### PR DESCRIPTION
**Pull request by eryugey**
# vHost
A crate to support vhost backend drivers for virtio devices.

## Kernel-based vHost Backend Drivers
The vhost drivers in Linux provide in-kernel virtio device emulation. Normally the hypervisor userspace process emulates I/O accesses from the guest. Vhost puts virtio emulation code into the kernel, taking hypervisor userspace out of the picture. This allows device emulation code to directly call into kernel subsystems instead of performing system calls from userspace. The hypervisor relies on ioctl based interfaces to control those in-kernel vhost drivers, such as vhost-net, vhost-scsi and vhost-vsock etc.

## vHost-user Backend Drivers
The vhost-user protocol is aiming to implement vhost backend drivers in userspace, which complements the ioctl interface used to control the vhost implementation in the Linux kernel. It implements the control plane needed to establish virtqueue sharing with a user space process on the same host. It uses communication over a Unix domain socket to share file descriptors in the ancillary data of the message.

The protocol defines two sides of the communication, master and slave. Master is the application that shares its virtqueues, slave is the consumer of the virtqueues. Master and slave can be either a client (i.e. connecting) or server (listening) in the socket communication.

### CODE REVIEW

**Comment by sameo** [comment]
@sboeuf This PR is a dump of @jiangliu's jiangliu/v1 branch, which is what our vhost_rs crate is based on.

I'd like us to be able to switch to this external crate (cloud-hypervisor/vhost) but first we would need to port our vhost_rs patches on top of it. So I'd like to get your review on this PR and check that if we merge it, we will be able to port our patches as a follow up PR. Could you PTAL?

**Comment by sboeuf** [comment]
@sameo I'll have a look!

**Comment by sboeuf** [comment]
@sameo I've just run a `diff` between this PR and the content of what we have on `cloud-hypervisor/cloud-hypervisor/vhost_rs`, and I don't see any blocker to apply the fixes we applied on `cloud-hypervisor/cloud-hypervisor/vhost_rs`.
When we do the porting of these fixes, we should try to find each patch that has been submitted as it will come with an explanation about why this was needed.

**Comment by jiangliu** [comment]
> @sameo I've just run a `diff` between this PR and the content of what we have on `cloud-hypervisor/cloud-hypervisor/vhost_rs`, and I don't see any blocker to apply the fixes we applied on `cloud-hypervisor/cloud-hypervisor/vhost_rs`.
> When we do the porting of these fixes, we should try to find each patch that has been submitted as it will come with an explanation about why this was needed.

Great, this also helps us to decide which patch to backport:)

**Comment by jiangliu** [comment]
We are also porting the virtio-fs implementation, which also depends on the vhost crate.

**Pull request merged**
